name: Publish Docker image for Shell (ARM64)

on:
    push:
        paths-ignore:
            - "README.md"
            - "javascript/**"
            - ".github/workflows/publish-js.yml"

jobs:
    build-and-push-shell-arm64-image:
        name: Build and push shell docker image (ARM64) to ghcr.io
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to the container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push shell docker image (ARM64)
              uses: docker/build-push-action@v5
              with:
                  context: ./shell
                  push: true
                  platforms: linux/arm64
                  tags: |
                      ghcr.io/doganm95/dynu-ddns-updater-shell-arm64:v1.${{ github.run_number }}
                      ghcr.io/doganm95/dynu-ddns-updater-shell-arm64:${{ github.sha }}
                      ghcr.io/doganm95/dynu-ddns-updater-shell-arm64:latest
                  labels: |
                      org.opencontainers.image.source=${{ github.repository_url }}
                      org.opencontainers.image.revision=${{ github.sha }}
