name: Publish Docker image for JavaScript

on:
    push:
        paths-ignore:
            - "README.md"
            - "shell/**"
            - ".github/workflows/publish-shell.yml"

jobs:
    build-and-push-js-image:
        name: Build and push JavaScript docker image to ghcr.io
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Log in to the container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push JavaScript docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./javascript
                  push: true
                  tags: |
                      ghcr.io/doganm95/dynu-ddns-updater-js:v1.${{ github.run_number }}
                      ghcr.io/doganm95/dynu-ddns-updater-js:${{ github.sha }}
                      ghcr.io/doganm95/dynu-ddns-updater-js:latest
                  labels: |
                      org.opencontainers.image.source=${{ github.repository_url }}
                      org.opencontainers.image.revision=${{ github.sha }}
